apiVersion: v1
kind: Service
metadata:
  name: service-maintenance-tasks
spec:
  selector:
    deployment: service-maintenance-tasks
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: main
  type: ClusterIP
